model: 'YOLO'
dataset_name: 'POSCAL'
classes: 1
in_channels: 3
train_list: '../dataset/extract_coco_train_test.txt'
val_list: '../dataset/extract_coco_train_test.txt'
names: './dataset/names/filter_coco.txt'
input_size: 448

gpus: 0
workers: 2
epochs: 500
batch_size: 2

save_freq: 1
save_dir: './saved'

# model Define
backbone: 'YOLOv1'
head: 'YOLOv1_Head'

optimizer: 'adam'
optimizer_options:
  lr: 1e-3
#  nesterov: true
#  momentum: 0.9
  weight_decay: 5e-4

loss: 'YOLOv1_loss'

trainer_options:
  check_val_every_n_epoch: 5
  
# YOLO Parameter
grid_size: 7
num_boxes: 2
